apiVersion: v2
appVersion: v2.0.2
description: A Helm chart for customizing the deployment of the Ansible Automation Platform Operator
name: ansible-automation-platform
version: 0.0.8
home: https://github.com/redhat-cop/helm-charts
maintainers:
- name: paulbarfuss
- name: ecda909
- name: jfilipcz
dependencies:
  - name: operatorhub
    version: "0.0.11"
    repository: https://redhat-cop.github.io/helm-charts
    condition: operatorhub.enabled
