---
name: Install Unit Tests

on:
  pull_request:
    paths:
    - .github/**
    - charts/**

# Declare default permissions as read only.
permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0

    - name: Setup chart-testing 🧰
      uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1
    
    - name: Find changed Charts 🔎
      id: changed-charts
      run: |
        changed=$(ct list-changed --target-branch main)
        echo ${changed}
        if [[ -n "$changed" ]]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    # set up kind cluster (using re-usable local composite action)
    - name: Setup Kind Cluster for Helm Chart Testing 🧰
      uses: ./.github/actions/setup-kind-cluster-for-helm-chart-testing
      if: steps.changed-charts.outputs.changed == 'true'

    - name: Run unit tests 🧪
      timeout-minutes: 30
      run: |
        ct install --target-branch main --debug --config _test/ct-config.yaml
      if: steps.changed-charts.outputs.changed == 'true'
