kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 5000
    hostPort: 5000
    protocol: TCP
  - containerPort: 80
    hostPort: 80
    protocol: TCP

# SOURCE: https://kind.sigs.k8s.io/docs/user/local-registry/
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
